config/routes.rb
Rent::Application.routes.draw do
  resources :vendors do
    resources :payments
  end

  
  root :to => "vendors#index"
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :vendor
  validates :amount, :presence => true
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  has_many :payments , :dependent => :destroy
  
  def payments_between(start_date, end_date)
   Payment.where("vendor_id = ? AND created_at BETWEEN ? AND ?", id, start_date, end_date)
  end

  def recent_payments
   start_date = weekly? ? Date.today.ago(1.week) : Date.today.ago(1.month)

   payments_between(start_date, Time.now)
  end

  def total_paid

    total = 0
    if recent_payments != nil 
      recent_payments.each do |payment|
        if payment.amount != nil
          total += payment.amount
        end
      end
    end

    return total
    
    
  end

  def paid_up?
    if debt <= 0.0
      true
    else
      false
    end
  end

  def debt
   amount - total_paid
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def create
    @vendor = Vendor.find(params[:vendor_id])
    @payment = @vendor.payments.create(params[:payment])
    redirect_to vendor_path(@vendor)
  end




end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  respond_to :html, :json

  def show
    @vendor = Vendor.find(params[:id])
    @recent_payments = Payment.where("vendor_id = ?", @vendor.id).order('created_at DESC').take(5)
    
  end

  def index
    @vendors = Vendor.all
    respond_with @vendors
  end

  def new
    @vendor = Vendor.new
  end

  def create
    @vendor = Vendor.create(params[:vendor])

    if @vendor.save
      #respond_with @vendor, notice: "Added Vendor"
      respond_with @vendor
    else
      render :new #, alert: "Something went wrong"
    end
  end
  
  def edit
    @vendor = Vendor.find(params[:id])
  end
  
  def update
    @vendor = Vendor.find(params[:id])

    respond_to do |format|
      if @vendor.update_attributes(params[:vendor])
        format.html { redirect_to(@vendor,
                      :notice => 'Vendor was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @vendor.errors,
                      :status => :unprocessable_entity }
      end
    end
  end
  
    
  
  def destroy
    @vendor = Vendor.find(params[:id])
    @vendor.destroy
    redirect_to(vendors_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rent</title>
  
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	
	<%= link_to 'Vendor List', vendors_path %>
<%= yield %>

</body>
</html>

app/views/vendors/_form.html.erb
<% #SimpleForm.wrapper_tag = :p%>
<%= simple_form_for @vendor do |f| %>
<%= f.input :name, :label =>  'Vendor\' name'%>
<%= f.input :booth, :label => 'Booth Number' %>
<%= f.input :amount, :label => 'Rent' %>
<p>
	<%= f.collection_radio :weekly, [[true, 'Weekly'] ,[false, 'Monthly']], :first, :last %>
</p>

<%= f.input :notes, :label=> 'Notes' , :input_html => {:rows => '5'}%>
<%= f.button :submit %>
<% end %>

app/views/vendors/edit.html.erb
<%= render 'form'%>

<%= link_to 'Home', vendors_path %>
<%= link_to 'Back to Vendor', @vendor %>

app/views/vendors/index.html.erb
<h1>Vendors</h1>
<table id = 'vendors'>
	<tr>
		<td><strong>Name</strong></td>
		<td><strong>Booth</strong></td>
		<td><strong>Rent</strong></td>
		<td><strong>Type</strong></td>
		<td><strong>Payment</strong></td>
	</tr>

  <% @vendors.each do |vendor| %>
		<tr>
        <td><%= link_to vendor.name, vendor %></td>
				<td><%= vendor.booth %></td>
				<td><%= number_to_currency(vendor.amount)%></td>
				<td>
				<% if vendor.weekly == true %>
					Weekly
				<% else %>
					Monthly
				<% end %>
				</td>
				<td>
					<% if vendor.paid_up? %>
						PAID
					<% else %>
						UNPAID
					<% end %>
				</td>
			</tr>
  <% end %>
</table>

<%= link_to "New Vendor", new_vendor_path%>

app/views/vendors/new.html.erb
<h1>New Vendor</h1>
<%= render 'form'%>

<%= link_to 'Back', vendors_path %>

app/views/vendors/show.html.erb
<h2><%= @vendor.name %></h2>

<div id='notes'>
	<h2>Notes:</h2>
	<p><%= @vendor.notes %></p>
</div>
<p>Booth Number: <%= @vendor.booth%></p>
<p>Rent: <%= number_to_currency(@vendor.amount) %></p>
<p>Type: 
	<% if @vendor.weekly == true %>
	 Weekly
	<% else %>
		Monthly
	<% end %>
</p>
<% if @vendor.paid_up? %>
	<h3>PAID</h3>
<% else %>
	<h3>UNPAID</h3>
<% end %>

<h3>Payments</h3>
	<% @recent_payments.each do |p| %>
		<p>Paid <%= number_to_currency(p.amount) %> at <%= p.created_at.month %>-<%= p.created_at.day%>-<%= p.created_at.year%></p>
	<% end %>

<% simple_form_for ([@vendor, @vendor.payments.build]) do |f| %>
	<%= f.input :amount, :label => 'Payment amount:' %>

	<%= f.button :submit %>
<% end %>

<%= link_to 'Edit', edit_vendor_path(@vendor)%>
<%= link_to 'Delete Vendor', @vendor, :confirm => 'Are you sure you want to delete this vendor?', :method => :delete%>